### ISSUE TITLE
Error in vagrant up ==> default: Unknown function contain at /etc/puppet/modules/nodejs/manifests/repo/nodesource.pp:97 on node precise64.lan

### ISSUE THREAD

**Issue by oudenaar** [cwhd/measurementor#1]
Hi Christopher,

I'm a reader of your new book, trying to run the measurementor. Although I ran it once successful, I'm starting over and run in some troubles during vagrant up:

==> default: Unknown function contain at /etc/puppet/modules/nodejs/manifests/repo/nodesource.pp:97 on node precise64.lan

I just checked the puppet code, but this seems to be normal?! Did you modify some code?

I hope you can help me out?!

BTW: I like your book, nice setup and perfect timing  where we current are in the DevOps field, combining with metrics.

K. Regards,
Bas

**Comment by oudenaar** [comment]
Commented on line 97, now it seems to work!
vagrant provision goes through...and I got responses on URLs

**Comment by dalpert-korewireless** [comment]
I also ran into this issue using fd08f5c on the `master` branch.

commenting out line 97 worked for me as well.
